export const SET_REPOSITORIES = "SET_REPOSITORIES";
export const DELETE_REPOSITORY = "DELETE_REPOSITORY";
export const ADD_REPOSITORY = "ADD_REPOSITORY";
export const UPDATE_REPOSITORY = "UPDATE_REPOSITORY";
